// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require, exports) {
    var compact, esprima, get_data, mode, mode_btn, q, render, source, target, whole;
    esprima = require("esprima");
    compact = require("compact");
    compact.render.hide = false;
    mode = "compact";
    q = function(query) {
      return document.querySelector(query);
    };
    source = q(".source");
    target = q(".target");
    mode_btn = q(".mode");
    render = function(data) {
      var content;
      content = mode === "compact" ? compact.render(data) : JSON.stringify(data, null, 2);
      return target.value = content;
    };
    get_data = function() {
      var error;
      try {
        return esprima.parse(source.value, {
          loc: true
        });
      } catch (_error) {
        error = _error;
        return error.toString();
      }
    };
    whole = function() {
      return render(get_data());
    };
    mode_btn.onclick = function() {
      mode = mode === "compact" ? "json" : "compact";
      return whole();
    };
    source.onkeyup = function() {
      target.value = "";
      return whole();
    };
    return whole();
  });

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
